# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
# permalink:        pretty
permalink: /:title/
# relative_permalinks: true

# Setup
title:            乐读汇
tagline:          'The happy read confluence'
#description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
description:      'Together, we are building a village, a community and an experience.'
url:              https://leducon.github.io
baseurl:          https://leducon.github.io
homepage:         https://leducon.github.io

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          0.3.0

github:
  repo:           https://github.com/leducon/leducon.github.io


